#- name: sample_book
#  hosts: root
#  remote_user: root
#  become: true
#  tasks:
#    - name: Run nexus container
#      command: docker start nexus
#      ignore_errors: yes
#    - name: Run SonarQube container
#      command: docker start sonarqueb
#      ignore_errors: yes
---
- name: Test Ansible connectivity
  hosts: localhost
  tasks:
    - name: Check connectivity
      command: echo "Ansible is working"
    - name: Run Nexus container
      command: docker start nexus
      ignore_errors: yes
    - name: Run SonarQube container
      command: docker start sonarqueb
      ignore_errors: yes
    - name: Run MySQL container
      command: docker start mysqldb
      ignore_errors: yes
    - name: Run cAdvisor container
      command: docker start cadvisor
      ignore_errors: yes
    - name: Run Prometheus container
      command: docker start prometheus
      ignore_errors: yes
    - name: Run Grafana container
      command: docker start grafana
      ignore_errors: yes