- name: sample_book
  hosts: localhost
  remote_user: root
  become: true
  tasks:
    - name: Run nexus container
      command: docker start nexus
      ignore_errors: yes
    - name: Run SonarQube container
      command: docker start sonarqueb
      ignore_errors: yes
