version: "3"
services:
  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    image: khaterkhrouf/discovery-service

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8888:9999"
    image: khaterkhrouf/gateway-service
    depends_on:
      - discovery-service
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/


#  front-service:
#    ports:
#      - "4202:4200"
#    image: "angular-dockerv1.1"
#    depends_on:
#      - user-service
#



  user-service:
    image: khaterkhrouf/user-service
    restart: always
    build: ./user-service
    ports:
      - 8001:8001
    depends_on:
      - mysqldb
    environment:
      - "SPRING_APPLICATION_JSON={ \"spring.datasource.url\" : \"jdbc:mysql://mysqldb:3306/userDocker?createDatabaseIfNotExist=true\", \"spring.datasource.username\" : \"root\", \"spring.datasource.password\" : \"root\" }"
      - "eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/"
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: userDocker
      #MYSQL_PASSWORD: "password"
#      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
volumes:
  mysql-data: